name: local_db_app
description: "A Flutter project with local DB for all platforms."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Drift database
  drift: ^2.17.0

  # Native platforms (Android, iOS, Desktop)
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.9.0

  # Password hashing
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code generation
  drift_dev: ^2.17.0
  build_runner: ^2.4.8